DATAS  SEGMENT USE16
	SUM DW ?
	COUNT DB 0
DATAS  ENDS

STACKS  SEGMENT USE16
STACKS  ENDS

CODES  SEGMENT
     ASSUME    CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    MOV AL,11
    ADD AL,20
    MOV CX,3
    ;MOV AX,AL
    ;DIV BH
    ;ADD AL,30H
    ;MOV AH,02H
    ;INT 21H
    ;ADD AH,30H
    ;MOV AH,02H
    ;INT 21H
SHIWEI:
    SUB AL,10
    INC COUNT
    LOOP SHIWEI
    
NEXT:
    ADD COUNT,30H
    MOV DL,COUNT
    MOV AH,02H
    INT 21H
    SUB AL,30H
    MOV DL,AL
    MOV AH,02H
    INT 21H
    
    MOV AH,4CH ;程序执行完毕，退出到系统
    INT 21H
   
CODES  ENDS
    END  START
